name: Validate JSON

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate brands-company-mapping.json
        run: |
          jq empty brands-company-mapping.json
